name: CI

on:
  schedule:
    - cron: '38 11 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    # tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: rsmnarts/kowl

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: cloudhut/kowl
      -
        name: Extract ref/branch name
        shell: bash
        run: echo "##[set-output name=ref;]$(echo ${GITHUB_REF##*/})"
        id: extract_ref
      -
        name: Set timestamp
        shell: bash
        run: echo "::set-output name=time::$(date +%s)"
        id: set_timestamp
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_UNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          build-args: |
            KOWL_GIT_SHA=${{ github.sha }}
            KOWL_GIT_REF=${{ steps.extract_ref.outputs.ref }}
            KOWL_TIMESTAMP=${{ steps.set_timestamp.outputs.time }}
            BUILT_FROM_PUSH=${{ github.event.action != 'published' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
      - 
        name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
